---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 0.1.0
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.1.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Set `common` chart dependency to version 0.1.0
