---
apiVersion: v2
description: Kubernetes admission controller to remove CPU limits from Pods.
name: k8s-ycl
version: 1.3.3
appVersion: v0.2.0
kubeVersion: ">=1.22.0-0"
sources:
  - https://github.com/bjw-s/k8s-ycl
keywords:
  - cpu
  - resources
  - limits
  - admission
  - controller
dependencies:
  - name: common
    repository: "file://../../library/common"
    version: 3.6.0
